name: Reusable - build and push docker image to GHCR

on:
  workflow_call:
    inputs:
      working-dir:
        type: string
        required: true
      tag:
        type: string
        required: true
      image:
        type: string
        required: true
    secrets:
      github-token:
        required: true
    outputs:
      deployed-image:
        value: ${{ jobs.build-push-ghcr.outputs.deployed-image }}

jobs:
  build-push-ghcr:
    outputs:
      deployed-image: ${{ steps.docker-push.outputs.image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Image
        id: lowercase_image
        run: echo "lc_image=$(echo '${{ inputs.image }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Run Tests
        working-directory: ${{ inputs.working-dir }}
        run: npm run test

      - name: Build Docker image
        working-directory: ${{ inputs.working-dir }}
        run: |
          docker build -t ${{ steps.lowercase_image.outputs.lc_image }}:latest -t ${{ steps.lowercase_image.outputs.lc_image }}:${{ inputs.tag }} .

      - name: Push latest and Version tag Docker image to GitHub Packages
        id: docker-push
        run: |
          docker push ${{ steps.lowercase_image.outputs.lc_image }}:latest
          docker push ${{ steps.lowercase_image.outputs.lc_image }}:${{ inputs.tag }}
          image="${{ steps.lowercase_image.outputs.lc_image }}:${{ inputs.tag }}"
          echo "image=$image" >> $GITHUB_OUTPUT
          echo "Extracted image: $image"  # Debugging output